import 'dotenv/config';
import mongoose from 'mongoose';
import { connectToDatabase } from '../db/connect.js';
import { ProjectModel } from '../models/ProjectModel.js';
import { TaskModel } from '../models/TaskModel.js';
import { EmployeeModel } from '../models/EmployeeModel.js';
import { RiskMatrixModel } from '../models/RiskMatrixModel.js';
import { ScenarioModel } from '../models/ScenarioModel.js';
import { CalculationResultModel } from '../models/CalculationResultModel.js';
import type { Employee, MatrixCell, Project, ProjectTask, Scenario } from '../core/types/domain.js';

const mongoUri = process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/budget_app';

const project: Project = {
  id: 'project-advanced-platform',
  name: 'Веб-платформа управления заявками клиентов',
  description:
    'Расширенный демонстрационный проект для апробации модели бюджетирования: личный кабинет, административная панель, CRM-интеграция, уведомления и аналитическая отчетность.',
  budgetLimit: 3_200_000,
  deadlineDays: 95,
  minStabilityIndex: 0.68,
  workHoursPerDay: 8,
  minAllowedProbability: 0.25,
};

const tasks: ProjectTask[] = [
  {
    id: 'task-01-requirements',
    projectId: project.id,
    name: 'Сбор и анализ требований',
    stage: 'analytics',
    baseHours: 32,
    complexityLevel: 'L2',
    isCritical: true,
    order: 1,
    dependsOnTaskIds: [],
  },
  {
    id: 'task-02-business-processes',
    projectId: project.id,
    name: 'Описание бизнес-процессов',
    stage: 'analytics',
    baseHours: 28,
    complexityLevel: 'L2',
    isCritical: true,
    order: 2,
    dependsOnTaskIds: ['task-01-requirements'],
  },
  {
    id: 'task-03-tech-spec',
    projectId: project.id,
    name: 'Формирование технического задания',
    stage: 'analytics',
    baseHours: 36,
    complexityLevel: 'L3',
    isCritical: true,
    order: 3,
    dependsOnTaskIds: ['task-01-requirements', 'task-02-business-processes'],
  },
  {
    id: 'task-04-architecture',
    projectId: project.id,
    name: 'Проектирование архитектуры системы',
    stage: 'backend',
    baseHours: 40,
    complexityLevel: 'L4',
    isCritical: true,
    order: 4,
    dependsOnTaskIds: ['task-03-tech-spec'],
  },
  {
    id: 'task-05-db-design',
    projectId: project.id,
    name: 'Проектирование структуры БД',
    stage: 'backend',
    baseHours: 32,
    complexityLevel: 'L3',
    isCritical: true,
    order: 5,
    dependsOnTaskIds: ['task-03-tech-spec'],
  },
  {
    id: 'task-06-user-flows',
    projectId: project.id,
    name: 'Проектирование пользовательских сценариев',
    stage: 'design',
    baseHours: 28,
    complexityLevel: 'L2',
    isCritical: false,
    order: 6,
    dependsOnTaskIds: ['task-03-tech-spec'],
  },
  {
    id: 'task-07-cabinet-design',
    projectId: project.id,
    name: 'UI/UX-дизайн личного кабинета',
    stage: 'design',
    baseHours: 48,
    complexityLevel: 'L3',
    isCritical: true,
    order: 7,
    dependsOnTaskIds: ['task-06-user-flows'],
  },
  {
    id: 'task-08-admin-design',
    projectId: project.id,
    name: 'UI/UX-дизайн административной панели',
    stage: 'design',
    baseHours: 40,
    complexityLevel: 'L3',
    isCritical: false,
    order: 8,
    dependsOnTaskIds: ['task-06-user-flows'],
  },
  {
    id: 'task-09-auth',
    projectId: project.id,
    name: 'Разработка авторизации и ролей',
    stage: 'backend',
    baseHours: 56,
    complexityLevel: 'L3',
    isCritical: true,
    order: 9,
    dependsOnTaskIds: ['task-04-architecture', 'task-05-db-design'],
  },
  {
    id: 'task-10-requests-api',
    projectId: project.id,
    name: 'Разработка API заявок',
    stage: 'backend',
    baseHours: 72,
    complexityLevel: 'L4',
    isCritical: true,
    order: 10,
    dependsOnTaskIds: ['task-04-architecture', 'task-05-db-design'],
  },
  {
    id: 'task-11-users-api',
    projectId: project.id,
    name: 'Разработка API пользователей',
    stage: 'backend',
    baseHours: 48,
    complexityLevel: 'L3',
    isCritical: true,
    order: 11,
    dependsOnTaskIds: ['task-04-architecture', 'task-05-db-design'],
  },
  {
    id: 'task-12-crm-integration',
    projectId: project.id,
    name: 'CRM-интеграция',
    stage: 'integration',
    baseHours: 80,
    complexityLevel: 'L4',
    isCritical: true,
    order: 12,
    dependsOnTaskIds: ['task-10-requests-api'],
  },
  {
    id: 'task-13-cabinet-frontend',
    projectId: project.id,
    name: 'Frontend личного кабинета',
    stage: 'frontend',
    baseHours: 72,
    complexityLevel: 'L3',
    isCritical: true,
    order: 13,
    dependsOnTaskIds: ['task-07-cabinet-design', 'task-09-auth', 'task-10-requests-api'],
  },
  {
    id: 'task-14-admin-frontend',
    projectId: project.id,
    name: 'Frontend административной панели',
    stage: 'frontend',
    baseHours: 64,
    complexityLevel: 'L3',
    isCritical: false,
    order: 14,
    dependsOnTaskIds: ['task-08-admin-design', 'task-09-auth', 'task-11-users-api'],
  },
  {
    id: 'task-15-notifications',
    projectId: project.id,
    name: 'Разработка уведомлений',
    stage: 'backend',
    baseHours: 36,
    complexityLevel: 'L2',
    isCritical: false,
    order: 15,
    dependsOnTaskIds: ['task-10-requests-api', 'task-11-users-api'],
  },
  {
    id: 'task-16-frontend-api-integration',
    projectId: project.id,
    name: 'Интеграция frontend с API',
    stage: 'integration',
    baseHours: 56,
    complexityLevel: 'L3',
    isCritical: true,
    order: 16,
    dependsOnTaskIds: ['task-12-crm-integration', 'task-13-cabinet-frontend', 'task-14-admin-frontend'],
  },
  {
    id: 'task-17-test-cases',
    projectId: project.id,
    name: 'Подготовка тест-кейсов',
    stage: 'qa',
    baseHours: 32,
    complexityLevel: 'L2',
    isCritical: true,
    order: 17,
    dependsOnTaskIds: ['task-03-tech-spec'],
  },
  {
    id: 'task-18-functional-testing',
    projectId: project.id,
    name: 'Функциональное тестирование',
    stage: 'qa',
    baseHours: 56,
    complexityLevel: 'L3',
    isCritical: true,
    order: 18,
    dependsOnTaskIds: ['task-16-frontend-api-integration', 'task-17-test-cases'],
  },
  {
    id: 'task-19-load-testing',
    projectId: project.id,
    name: 'Нагрузочное тестирование API',
    stage: 'qa',
    baseHours: 40,
    complexityLevel: 'L3',
    isCritical: false,
    order: 19,
    dependsOnTaskIds: ['task-10-requests-api', 'task-12-crm-integration'],
  },
  {
    id: 'task-20-stabilization',
    projectId: project.id,
    name: 'Исправление дефектов и стабилизация',
    stage: 'backend',
    baseHours: 48,
    complexityLevel: 'L3',
    isCritical: true,
    order: 20,
    dependsOnTaskIds: ['task-18-functional-testing', 'task-19-load-testing'],
  },
  {
    id: 'task-21-documentation',
    projectId: project.id,
    name: 'Подготовка пользовательской документации',
    stage: 'analytics',
    baseHours: 24,
    complexityLevel: 'L2',
    isCritical: false,
    order: 21,
    dependsOnTaskIds: ['task-16-frontend-api-integration'],
  },
  {
    id: 'task-22-release',
    projectId: project.id,
    name: 'Развертывание и релиз',
    stage: 'deployment',
    baseHours: 32,
    complexityLevel: 'L3',
    isCritical: true,
    order: 22,
    dependsOnTaskIds: ['task-20-stabilization', 'task-21-documentation'],
  },
];

const employees: Employee[] = [
  {
    id: 'emp-middle-analyst',
    name: 'Middle analyst',
    role: 'analyst',
    grade: 'middle',
    hourRate: 2_200,
    availability: 1,
  },
  {
    id: 'emp-senior-analyst',
    name: 'Senior analyst',
    role: 'analyst',
    grade: 'senior',
    hourRate: 3_000,
    availability: 1,
  },
  {
    id: 'emp-middle-designer',
    name: 'Middle UI/UX designer',
    role: 'designer',
    grade: 'middle',
    hourRate: 2_000,
    availability: 1,
  },
  {
    id: 'emp-senior-designer',
    name: 'Senior UI/UX designer',
    role: 'designer',
    grade: 'senior',
    hourRate: 2_800,
    availability: 1,
  },
  {
    id: 'emp-junior-frontend',
    name: 'Junior frontend developer',
    role: 'frontend',
    grade: 'junior',
    hourRate: 1_400,
    availability: 1,
  },
  {
    id: 'emp-middle-frontend',
    name: 'Middle frontend developer',
    role: 'frontend',
    grade: 'middle',
    hourRate: 2_300,
    availability: 1,
  },
  {
    id: 'emp-senior-frontend',
    name: 'Senior frontend developer',
    role: 'frontend',
    grade: 'senior',
    hourRate: 3_200,
    availability: 1,
  },
  {
    id: 'emp-junior-backend',
    name: 'Junior backend developer',
    role: 'backend',
    grade: 'junior',
    hourRate: 1_500,
    availability: 1,
  },
  {
    id: 'emp-middle-backend',
    name: 'Middle backend developer',
    role: 'backend',
    grade: 'middle',
    hourRate: 2_600,
    availability: 1,
  },
  {
    id: 'emp-senior-backend',
    name: 'Senior backend developer',
    role: 'backend',
    grade: 'senior',
    hourRate: 3_700,
    availability: 1,
  },
  {
    id: 'emp-middle-integration',
    name: 'Middle integration developer',
    role: 'integration',
    grade: 'middle',
    hourRate: 2_800,
    availability: 1,
  },
  {
    id: 'emp-senior-integration',
    name: 'Senior integration developer',
    role: 'integration',
    grade: 'senior',
    hourRate: 3_900,
    availability: 1,
  },
  {
    id: 'emp-middle-qa',
    name: 'Middle QA engineer',
    role: 'qa',
    grade: 'middle',
    hourRate: 1_900,
    availability: 1,
  },
  {
    id: 'emp-senior-qa',
    name: 'Senior QA engineer',
    role: 'qa',
    grade: 'senior',
    hourRate: 2_700,
    availability: 1,
  },
  {
    id: 'emp-devops',
    name: 'DevOps engineer',
    role: 'devops',
    grade: 'middle',
    hourRate: 3_000,
    availability: 1,
  },
];

const matrix: MatrixCell[] = [
  { grade: 'intern', complexityLevel: 'L1', probability: 0.80, deltaDays: 3 },
  { grade: 'intern', complexityLevel: 'L2', probability: 0.35, deltaDays: 7 },
  { grade: 'intern', complexityLevel: 'L3', probability: 0.10, deltaDays: 12 },
  { grade: 'intern', complexityLevel: 'L4', probability: 0.02, deltaDays: 18 },

  { grade: 'junior', complexityLevel: 'L1', probability: 0.90, deltaDays: 2 },
  { grade: 'junior', complexityLevel: 'L2', probability: 0.70, deltaDays: 4 },
  { grade: 'junior', complexityLevel: 'L3', probability: 0.30, deltaDays: 8 },
  { grade: 'junior', complexityLevel: 'L4', probability: 0.10, deltaDays: 14 },

  { grade: 'middle', complexityLevel: 'L1', probability: 0.97, deltaDays: 1 },
  { grade: 'middle', complexityLevel: 'L2', probability: 0.88, deltaDays: 2 },
  { grade: 'middle', complexityLevel: 'L3', probability: 0.65, deltaDays: 5 },
  { grade: 'middle', complexityLevel: 'L4', probability: 0.30, deltaDays: 6 },

  { grade: 'senior', complexityLevel: 'L1', probability: 0.99, deltaDays: 1 },
  { grade: 'senior', complexityLevel: 'L2', probability: 0.95, deltaDays: 1 },
  { grade: 'senior', complexityLevel: 'L3', probability: 0.85, deltaDays: 3 },
  { grade: 'senior', complexityLevel: 'L4', probability: 0.70, deltaDays: 3 },
];

const scenarioA: Scenario = {
  id: 'scenario-a',
  projectId: project.id,
  name: 'A – экономичный',
  description:
    'Сценарий с преобладанием middle-исполнителей и junior frontend на части интерфейсных задач. Минимизирует ставку, но повышает риск по сроку.',
  teamFitCoefficient: 0.78,
  deltaMode: 'criticalOnly',
  assignments: [
    { taskId: 'task-01-requirements', employeeId: 'emp-middle-analyst', allocation: 1 },
    { taskId: 'task-02-business-processes', employeeId: 'emp-middle-analyst', allocation: 1 },
    { taskId: 'task-03-tech-spec', employeeId: 'emp-middle-analyst', allocation: 1 },
    { taskId: 'task-04-architecture', employeeId: 'emp-middle-backend', allocation: 1 },
    { taskId: 'task-05-db-design', employeeId: 'emp-middle-backend', allocation: 1 },
    { taskId: 'task-06-user-flows', employeeId: 'emp-middle-designer', allocation: 1 },
    { taskId: 'task-07-cabinet-design', employeeId: 'emp-middle-designer', allocation: 1 },
    { taskId: 'task-08-admin-design', employeeId: 'emp-middle-designer', allocation: 1 },
    { taskId: 'task-09-auth', employeeId: 'emp-middle-backend', allocation: 1 },
    { taskId: 'task-10-requests-api', employeeId: 'emp-middle-backend', allocation: 1 },
    { taskId: 'task-11-users-api', employeeId: 'emp-middle-backend', allocation: 1 },
    { taskId: 'task-12-crm-integration', employeeId: 'emp-middle-integration', allocation: 1 },
    { taskId: 'task-13-cabinet-frontend', employeeId: 'emp-junior-frontend', allocation: 1 },
    { taskId: 'task-14-admin-frontend', employeeId: 'emp-junior-frontend', allocation: 1 },
    { taskId: 'task-15-notifications', employeeId: 'emp-middle-backend', allocation: 1 },
    { taskId: 'task-16-frontend-api-integration', employeeId: 'emp-middle-integration', allocation: 1 },
    { taskId: 'task-17-test-cases', employeeId: 'emp-middle-qa', allocation: 1 },
    { taskId: 'task-18-functional-testing', employeeId: 'emp-middle-qa', allocation: 1 },
    { taskId: 'task-19-load-testing', employeeId: 'emp-middle-qa', allocation: 1 },
    { taskId: 'task-20-stabilization', employeeId: 'emp-middle-backend', allocation: 1 },
    { taskId: 'task-21-documentation', employeeId: 'emp-middle-analyst', allocation: 1 },
    { taskId: 'task-22-release', employeeId: 'emp-devops', allocation: 1 },
  ],
};

const scenarioB: Scenario = {
  id: 'scenario-b',
  projectId: project.id,
  name: 'B – сбалансированный',
  description:
    'Критичные L4 и интеграционные задачи усилены senior-исполнителями, при этом часть типовых задач остается за middle-специалистами.',
  teamFitCoefficient: 0.88,
  deltaMode: 'criticalOnly',
  assignments: [
    { taskId: 'task-01-requirements', employeeId: 'emp-senior-analyst', allocation: 1 },
    { taskId: 'task-02-business-processes', employeeId: 'emp-middle-analyst', allocation: 1 },
    { taskId: 'task-03-tech-spec', employeeId: 'emp-senior-analyst', allocation: 1 },
    { taskId: 'task-04-architecture', employeeId: 'emp-senior-backend', allocation: 1 },
    { taskId: 'task-05-db-design', employeeId: 'emp-middle-backend', allocation: 1 },
    { taskId: 'task-06-user-flows', employeeId: 'emp-middle-designer', allocation: 1 },
    { taskId: 'task-07-cabinet-design', employeeId: 'emp-senior-designer', allocation: 1 },
    { taskId: 'task-08-admin-design', employeeId: 'emp-middle-designer', allocation: 1 },
    { taskId: 'task-09-auth', employeeId: 'emp-middle-backend', allocation: 1 },
    { taskId: 'task-10-requests-api', employeeId: 'emp-senior-backend', allocation: 1 },
    { taskId: 'task-11-users-api', employeeId: 'emp-middle-backend', allocation: 1 },
    { taskId: 'task-12-crm-integration', employeeId: 'emp-senior-integration', allocation: 1 },
    { taskId: 'task-13-cabinet-frontend', employeeId: 'emp-middle-frontend', allocation: 1 },
    { taskId: 'task-14-admin-frontend', employeeId: 'emp-middle-frontend', allocation: 1 },
    { taskId: 'task-15-notifications', employeeId: 'emp-middle-backend', allocation: 1 },
    { taskId: 'task-16-frontend-api-integration', employeeId: 'emp-senior-integration', allocation: 1 },
    { taskId: 'task-17-test-cases', employeeId: 'emp-middle-qa', allocation: 1 },
    { taskId: 'task-18-functional-testing', employeeId: 'emp-senior-qa', allocation: 1 },
    { taskId: 'task-19-load-testing', employeeId: 'emp-middle-qa', allocation: 1 },
    { taskId: 'task-20-stabilization', employeeId: 'emp-senior-backend', allocation: 1 },
    { taskId: 'task-21-documentation', employeeId: 'emp-middle-analyst', allocation: 1 },
    { taskId: 'task-22-release', employeeId: 'emp-devops', allocation: 1 },
  ],
};

const scenarioC: Scenario = {
  id: 'scenario-c',
  projectId: project.id,
  name: 'C – усиленный',
  description:
    'На большинстве критичных задач используются senior-исполнители. Сценарий повышает устойчивость и сокращает календарный срок, но увеличивает бюджет.',
  teamFitCoefficient: 0.94,
  deltaMode: 'criticalOnly',
  assignments: [
    { taskId: 'task-01-requirements', employeeId: 'emp-senior-analyst', allocation: 1 },
    { taskId: 'task-02-business-processes', employeeId: 'emp-senior-analyst', allocation: 1 },
    { taskId: 'task-03-tech-spec', employeeId: 'emp-senior-analyst', allocation: 1 },
    { taskId: 'task-04-architecture', employeeId: 'emp-senior-backend', allocation: 1 },
    { taskId: 'task-05-db-design', employeeId: 'emp-senior-backend', allocation: 1 },
    { taskId: 'task-06-user-flows', employeeId: 'emp-senior-designer', allocation: 1 },
    { taskId: 'task-07-cabinet-design', employeeId: 'emp-senior-designer', allocation: 1 },
    { taskId: 'task-08-admin-design', employeeId: 'emp-senior-designer', allocation: 1 },
    { taskId: 'task-09-auth', employeeId: 'emp-senior-backend', allocation: 1 },
    { taskId: 'task-10-requests-api', employeeId: 'emp-senior-backend', allocation: 1 },
    { taskId: 'task-11-users-api', employeeId: 'emp-senior-backend', allocation: 1 },
    { taskId: 'task-12-crm-integration', employeeId: 'emp-senior-integration', allocation: 1 },
    { taskId: 'task-13-cabinet-frontend', employeeId: 'emp-senior-frontend', allocation: 1 },
    { taskId: 'task-14-admin-frontend', employeeId: 'emp-senior-frontend', allocation: 1 },
    { taskId: 'task-15-notifications', employeeId: 'emp-senior-backend', allocation: 1 },
    { taskId: 'task-16-frontend-api-integration', employeeId: 'emp-senior-integration', allocation: 1 },
    { taskId: 'task-17-test-cases', employeeId: 'emp-senior-qa', allocation: 1 },
    { taskId: 'task-18-functional-testing', employeeId: 'emp-senior-qa', allocation: 1 },
    { taskId: 'task-19-load-testing', employeeId: 'emp-senior-qa', allocation: 1 },
    { taskId: 'task-20-stabilization', employeeId: 'emp-senior-backend', allocation: 1 },
    { taskId: 'task-21-documentation', employeeId: 'emp-senior-analyst', allocation: 1 },
    { taskId: 'task-22-release', employeeId: 'emp-devops', allocation: 1 },
  ],
};

const scenarios: Scenario[] = [scenarioA, scenarioB, scenarioC];

await connectToDatabase(mongoUri);

// Этот seed полностью заменяет текущие демонстрационные данные.
// Перед запуском лучше сделать бэкап MongoDB.
await Promise.all([
  ProjectModel.deleteMany({}),
  TaskModel.deleteMany({}),
  EmployeeModel.deleteMany({}),
  RiskMatrixModel.deleteMany({}),
  ScenarioModel.deleteMany({}),
  CalculationResultModel.deleteMany({}),
]);

await ProjectModel.create({ _id: project.id, ...project });
await TaskModel.insertMany(tasks.map((task) => ({ _id: task.id, ...task })));
await EmployeeModel.insertMany(employees.map((employee) => ({ _id: employee.id, ...employee })));

await RiskMatrixModel.create({
  _id: 'risk-matrix-advanced-v1',
  name: 'Экспертная матрица для расширенного проекта',
  version: 'advanced-1.0',
  isDefault: true,
  cells: matrix,
});

await ScenarioModel.insertMany(scenarios.map((scenario) => ({ _id: scenario.id, ...scenario })));

console.log('Расширенный демонстрационный проект загружен в MongoDB');
console.log(`Проект: ${project.name}`);
console.log(`Задач: ${tasks.length}`);
console.log(`Исполнителей: ${employees.length}`);
console.log(`Сценариев: ${scenarios.length}`);

await mongoose.disconnect();
